spring:
  application:
    name: store_management
  datasource:
    url: jdbc:h2:mem:storedb
    driver-class-name: org.h2.Driver
    username: storemanager
    password: storemanager
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
    #org.springframework.web: DEBUG
    com.inghubs.storemanager.store_management: DEBUG
